apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: ticketing-microservices-site
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-344501
  artifacts:
    - image: us.gcr.io/ticketing-dev-344501/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .  
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
